source('scripts/monthly_patient_graphics.R')
root <- tempfile('amma-report-check-')
dir.create(file.path(root, 'processed/runs/test'), recursive = TRUE)
write_json(list(status='passed', relative_path='runs/test', run_id='test'), file.path(root,'processed/latest.json'), auto_unbox=TRUE)
write_json(list(status='passed'), file.path(root,'processed/runs/test/run_manifest.json'), auto_unbox=TRUE)
days <- tidyr::expand_grid(participant_id=c('TEST-A','TEST-B'), date=seq(as.Date('2024-02-01'),as.Date('2024-03-02'),by='day')) |>
 mutate(seizure_status='confirmed_none', seizure_count=0, sleep_quality=rep(c('poor','fair','good',NA),length.out=n()), mood_rating=rep(c('red','yellow','green',NA),length.out=n()))
days$seizure_status[1:3] <- c('reported_seizure','missing','unknown')
days$seizure_count[1] <- 3
events <- tibble(participant_id=rep('TEST-A',3), observation_date=rep('2024-02-01',3), seizure_type=c('focal','focal',NA))
write_csv(days, file.path(root,'processed/runs/test/participant_days.csv'))
write_csv(events, file.path(root,'processed/runs/test/seizure_events.csv'))
demo_path <- file.path(root, 'demo.csv')
write_csv(tibble(`Participant ID`=c('TEST-A','TEST-B'), fname=c('Alex','Sam'), lname=c('Example','Sample')), demo_path)
index <- render_monthly_reports(file.path(root,'processed'),file.path(root,'reports'),demo_path)
stopifnot(nrow(index)==4, all(file.exists(index$file)))
stopifnot(all(grepl('\\.pdf$', index$file)), all(grepl('Alex_Example|Sam_Sample', index$file)))
stopifnot(rawToChar(readBin(index$file[1], 'raw', n=4)) == '%PDF')
stopifnot(!file.exists(file.path(root,'reports/seizure_type_colors.csv')))
days$seizure_count[1] <- 4
write_csv(days,file.path(root,'processed/runs/test/participant_days.csv'))
err <- tryCatch(render_monthly_reports(file.path(root,'processed'),file.path(root,'reports'),demo_path),error=identity)
stopifnot(inherits(err,'error'),grepl('reconcile',err$message))
unlink(root, recursive = TRUE)
cat('Monthly report checks passed\n')
