source('scripts/monthly_patient_graphics.R')
root <- tempfile('amma-report-check-')
run_dir <- file.path(root, 'processed-run')
dir.create(run_dir, recursive = TRUE)
write_json(list(status='passed', run_id='test'), file.path(run_dir,'run_manifest.json'), auto_unbox=TRUE)
days <- tidyr::expand_grid(participant_id=c('TEST-A','TEST-B'), date=seq(as.Date('2024-02-01'),as.Date('2024-03-02'),by='day')) |>
 mutate(seizure_status='confirmed_none', seizure_count=0, sleep_quality=rep(c('poor','fair','good',NA),length.out=n()), mood_rating=rep(c('red','yellow','green',NA),length.out=n()))
days$seizure_status[1:3] <- c('reported_seizure','missing','unknown')
days$seizure_count[1] <- 3
events <- tibble(participant_id=rep('TEST-A',3), observation_date=rep('2024-02-01',3), seizure_type=c('focal','focal',NA))
write_csv(days, file.path(run_dir,'participant_days.csv'))
write_csv(events, file.path(run_dir,'seizure_events.csv'))
demo_path <- file.path(root, 'demo.csv')
write_csv(tibble(`Participant ID`=c('TEST-A','TEST-B'), fname=c('Alex','Sam'), lname=c('Example','Sample')), demo_path)
index <- render_monthly_reports(run_dir,file.path(root,'reports'),demo_path)
stopifnot(nrow(index)==4, all(file.exists(index$file)))
stopifnot(all(grepl('\\.pdf$', index$file)), all(grepl('TEST-A|TEST-B', index$file)))
stopifnot(rawToChar(readBin(index$file[1], 'raw', n=4)) == '%PDF')
stopifnot(!file.exists(file.path(root,'reports/seizure_type_colors.csv')))
written_index <- read_csv(file.path(root,'reports/test/report_index.csv'), show_col_types=FALSE)
stopifnot(!('patient_name' %in% names(written_index)), !('file' %in% names(written_index)))
stopifnot(all(c('participant_id','month','source_run','relative_file') %in% names(written_index)))
report_manifest <- fromJSON(file.path(root,'reports/test/report_manifest.json'))
stopifnot(report_manifest$status=='passed', report_manifest$source_run_id=='test', report_manifest$report_count==4)
days$seizure_count[1] <- 4
write_csv(days,file.path(run_dir,'participant_days.csv'))
err <- tryCatch(render_monthly_reports(run_dir,file.path(root,'reports'),demo_path),error=identity)
stopifnot(inherits(err,'error'),grepl('reconcile',err$message))
unlink(root, recursive = TRUE)
cat('Monthly report checks passed\n')
